# Generated by Django 2.2 on 2019-04-10 07:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('logintest', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='FormTypes',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('type', models.CharField(
                    choices=[('1', '1.调账说明'), ('2', '2.未达账项'), ('3', '3.表单3'), ('4', '表单4'), ('5', '表单5')],
                    default='1.调账说明', max_length=128)),
                ('month', models.CharField(
                    choices=[('1', '1月',), ('2', '2月',), ('3', '3月',), ('4', '4月',), ('5', '5月',), ('6', '6月',),
                             ('7', '7月',), ('8', '8月',), ('9', '9月',), ('10', '10月',), ('11', '11月',), ('12', '12月',)],
                    default='1月', max_length=128)),
                ('user', models.CharField(max_length=256)),
                ('c_time2', models.DateTimeField(auto_now_add=True)),
                ('n_time', models.CharField(max_length=256)),
            ],
            options={
                'verbose_name': '文件',
                'verbose_name_plural': '文件',
                'ordering': ['c_time2'],
            },
        ),
    ]
